### ISSUE TITLE
QUESTION: how could I handle subsequent run after a failure and patching

### ISSUE THREAD

**Issue by brazarb** [leonardochaia/dotnet-affected-action#258]
Hi guys, thanks for the action.

I was using this action a year or so ago but ran into a problem, but had other priorities so forgot about this.

Scenario:

`featA` PR -> `base`

Solution with multiple projects, some projects depend on others etc...

action picks up that 3 projects are affected by the change.

But for some other reason, the workflow run fails, e.g. fail to deploy to Azure due to some error, e.g. syntax error in the deployment workflow.

Given the `featA` branch is already merged with `base` and lets say the branch is now deleted, I created a new branch `fixA` and PR that into `main`.

Now the action runs, but no longer detects any changes because the only file that changed was the deployment workflow.

How could I address this issue, in the event the workflow run fails, a code change to address the issue most likely will not affect the same projects or any project for that matter.

when running `dotnet affected` directly, one can pass the `--assume-changes` flag, I'm not sure if this is the solution, or if there's another approach for this problem, I've also noticed the `dotnet-affected-action` does not support the flag anyway, so if this would be the way to deal with this edge case, I would have to install dotnet affected tool and run it separately.

Please kindly advice

**Comment by leonardochaia** [comment]
Hi @brazarb , I think that the trick you are missing is to run dotnet affected between the current commit and the "last successful build" commit. This is explained [in the readme](https://dev.azure.com/abg-devops/Architecture%20and%20Operation/_build/results?buildId=96006&view=results)

Do let me know if you need more clarification :+1: , or if I misunderstood.
Leo

**Comment by brazarb** [comment]
Hi @leonardochaia , thanks for replying.

I don't have access to the link you added above, perhaps it was added by mistake?

I was referring to building PR's as described in the readme [for-building-prs](https://github.com/leonardochaia/dotnet-affected-action?tab=readme-ov-file#for-building-prs).

So I guess the answer is to use the [for-building-branches](https://github.com/leonardochaia/dotnet-affected-action?tab=readme-ov-file#for-building-branches) instead right?

If so, is there a case where one might want to use building for prs given the fact that in case of failure, subsequent run after a patch most likely will not result in the same affected.proj?

PS. I've noticed in the readme it suggests the use of `nrwl/last-successful-commit-action@v1`, but this action has been archived and replaced with [nx-set-shas](https://github.com/marketplace/actions/nx-set-shas)

**Comment by leonardochaia** [comment]
Hi @brazarb , sorry I pasted the wrong link. I've fixed my comment.

> If so, is there a case where one might want to use building for prs given the fact that in case of failure, subsequent run after a patch most likely will not result in the same affected.proj?

When building pull requests, you should be comparing your PR branch to your destination branch(usually main/master). When doing so, the affected projects will always be the diff between the PR branch and the destination branch, despite of the build status of main or the pr branch. In such case, building PRs, there's no need to use the "last successful build" trick 

For example: `dotnet affected --from=origin/main --to origin/features/my-feat`.

When the PR is merged, continuing with your scenario:

>  But for some other reason, the workflow run fails, e.g. fail to deploy to Azure due to some error, e.g. syntax error in the deployment workflow.
Given the featA branch is already merged with base and lets say the branch is now deleted, I created a new branch fixA and PR that into main.
Now the action runs, but no longer detects any changes because the only file that changed was the deployment workflow.

If the workflow failed, and you are using the "last successful build" trick on your main branch workflow, you should be fine since affected will do the git diff between the last successful build commit and the current one.

For a proper CI/CD you need to combine both: have a separate workflow for PRs that uses the source and destination branch for the diff, and have a separate workflow for main that uses the "last successfull commit" trick.


> PS. I've noticed in the readme it suggests the use of nrwl/last-successful-commit-action@v1, but this action has been archived and replaced with [nx-set-shas](https://github.com/marketplace/actions/nx-set-shas)

The replacement action seems to be pretty much the same, we should update this readme to reflect that.

**Comment by brazarb** [comment]
Awesome, thank you. I think with that information I'm more prepared for the change.
